### PR TITLE
I made this for you

### PR DESCRIPTION
**Pull request by djava**
I hope you like it. security is ALWAYS important. ty 💋

### CODE REVIEW

**Comment by djava** [comment]
lmk when this is gonna get accepted please. ty 💋

**Comment by djava** [comment]
Requesting review. I dont know how github works so just review it and email me back. thank!

**Comment by djava** [comment]
@NathanaelOliver do you like my changes? its for security

**Comment by NathanaelOliver** [comment]
Sorry, this page is not important to us right now and does not follow yhe conventions that we are using for this project.

**Pull request closed without merging**
